

jobs:
- name: say-hi
  plan:
  - task: echo
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: busybox
      run:
        path: echo
        args:
          - "Booo"
