resources:
- name: my-github-repo
  type: git
  source:
    uri: https://github.com/tamarabartlett/my-github-repo.git
    branch: master

jobs:
- name: say-hi
  plan:
  - get: my-github-repo
  - task: echo
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: busybox
      run:
        path: echo
        args:
          - "Booo"
